/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiKasirReping;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class PaymentForm extends javax.swing.JInternalFrame {

    public ArrayList menu = new ArrayList();
    public ArrayList harga = new ArrayList();
    public ArrayList jumlah = new ArrayList();
    public ArrayList subtotal = new ArrayList();
    
    public PaymentForm() {
        initComponents();
    }

    private void setHargaMakanan(){
        int harga = 0;
        int pilihan = menuMakananCb.getSelectedIndex();
        switch (pilihan){
            case 1:
                harga = 9000;
                break;
            case 2:
                harga = 10000;
            break;
            case 3:
                harga = 10000;
            break;
            case 4:
                harga = 12000;
            break;
        }
        hargaMakananTxt.setText("" + harga);
    }
    
    private void setHargaMinuman(){
    int harga = 0;
    if (menuMinumanCb.getSelectedIndex() == 0)
        harga = 0;
    else 
        harga = 2000;
    
    hargaMinumanTxt.setText("" + harga);
    }
    
    private void setTabel(){
        int total= 0;
        double pajak= 0;
        int bayar = 0;
        
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Menu");
        tbl.addColumn("Harga");
        tbl.addColumn("Jumlah");
        tbl.addColumn("Sub total");
        
        for(int n=0; n<menu.size(); n++){
            total = total + Integer.parseInt(subtotal.get(n).toString());
            
            tbl.addRow(new Object[]{
            menu.get(n),
            harga.get(n),
            jumlah.get(n),
            subtotal.get(n),
            });
        }
        pajak = total * 0.03;
        bayar = (int) (total + pajak);
        
        dataTabel.setModel(tbl);
        totalTxt.setText("" + total);
        ppnTxt.setText("" + pajak);
        totalBayarTxt.setText("" + bayar);
        
    }
    
    private boolean cekKosong(boolean makanan){
        boolean hasil = true;
        
        if(makanan == true){
            if(jumlahMakananTxt.getText().isEmpty() == true){
                JOptionPane.showMessageDialog(null, "jumlah makanan harus diisi");
                hasil = true;
            }
        }else{
            if(jumlahMakananTxt.getText().isEmpty() == true){
                JOptionPane.showMessageDialog(null, "jumlah makanan harus diisi");
            }
        }
        return false;
    }
    
    private boolean cekDataTabel(String data){
        boolean hasil = menu.contains(data);
        if(hasil == true) JOptionPane.showMessageDialog(null, "menu sudah ditambahkan.");
        return hasil;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hargaMakananTxt = new javax.swing.JTextField();
        jumlahMakananTxt = new javax.swing.JTextField();
        subTotalMakananTxt = new javax.swing.JTextField();
        menuMakananCb = new javax.swing.JComboBox<>();
        makananBtn = new javax.swing.JButton();
        tambahkanMakanBtn = new javax.swing.JButton();
        tambahkanMinumanBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hargaMinumanTxt = new javax.swing.JTextField();
        jumlahMinumanTxt = new javax.swing.JTextField();
        subTotalMinumanTxt = new javax.swing.JTextField();
        menuMinumanCb = new javax.swing.JComboBox<>();
        minumanBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTabel = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JTextField();
        ppnTxt = new javax.swing.JTextField();
        totalBayarTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jumlahBayarTxt = new javax.swing.JTextField();
        kembalianTxt = new javax.swing.JTextField();
        bayarBtn = new javax.swing.JButton();
        clearBt = new javax.swing.JButton();

        setTitle("ORDER PESANAN");

        jLabel1.setText("MENU MAKANAN");

        jLabel2.setText("HARGA");

        jLabel3.setText("JUMLAH");

        jLabel4.setText("JUMLAH TOTAL");

        hargaMakananTxt.setEditable(false);
        hargaMakananTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaMakananTxtActionPerformed(evt);
            }
        });

        subTotalMakananTxt.setEditable(false);

        menuMakananCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- PILIH -", "AYAM GEPREK", "NASI GORENG ", "MIE GORENG", "AYAM GORENG", " " }));
        menuMakananCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMakananCbActionPerformed(evt);
            }
        });

        makananBtn.setText("\"");
        makananBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makananBtnActionPerformed(evt);
            }
        });

        tambahkanMakanBtn.setText("TAMBAHKAN");
        tambahkanMakanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkanMakanBtnActionPerformed(evt);
            }
        });

        tambahkanMinumanBtn.setText("TAMBAHKAN");
        tambahkanMinumanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkanMinumanBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("MENU MINUMAN");

        jLabel6.setText("HARGA");

        jLabel7.setText("JUMLAH");

        jLabel8.setText("JUMLAH TOTAL");

        hargaMinumanTxt.setEditable(false);

        subTotalMinumanTxt.setEditable(false);
        subTotalMinumanTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTotalMinumanTxtActionPerformed(evt);
            }
        });

        menuMinumanCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- PILIH -", "ES TEH", "ES JERUK", "TEH HANGAT", "JERUK HANGAT", "KOPI", " " }));
        menuMinumanCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMinumanCbActionPerformed(evt);
            }
        });

        minumanBtn.setText("\"");
        minumanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minumanBtnActionPerformed(evt);
            }
        });

        dataTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Menu", "Harga", "Jumlah", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(dataTabel);

        jLabel9.setText("TOTAL");

        jLabel10.setText("Ppn (10%)");

        jLabel11.setText("TOTAL BAYAR");

        totalTxt.setEditable(false);

        ppnTxt.setEditable(false);

        totalBayarTxt.setEditable(false);

        jLabel12.setText("JUMLAH BAYAR");

        jLabel13.setText("KEMBALIAN");

        kembalianTxt.setEditable(false);

        bayarBtn.setText("BAYAR");
        bayarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarBtnActionPerformed(evt);
            }
        });

        clearBt.setText("CLEAR");
        clearBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(ppnTxt)
                            .addComponent(totalBayarTxt))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jumlahBayarTxt)
                                    .addComponent(kembalianTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clearBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bayarBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tambahkanMakanBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hargaMakananTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(subTotalMakananTxt)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jumlahMakananTxt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(makananBtn)))
                            .addComponent(menuMakananCb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hargaMinumanTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jumlahMinumanTxt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(minumanBtn))
                                .addComponent(subTotalMinumanTxt))
                            .addComponent(tambahkanMinumanBtn)
                            .addComponent(menuMinumanCb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(menuMinumanCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(hargaMinumanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jumlahMinumanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minumanBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(subTotalMinumanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tambahkanMinumanBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(menuMakananCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(hargaMakananTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jumlahMakananTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(makananBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(subTotalMakananTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tambahkanMakanBtn)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jumlahBayarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ppnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bayarBtn)
                    .addComponent(clearBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(totalBayarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(kembalianTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hargaMakananTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaMakananTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaMakananTxtActionPerformed

    private void menuMakananCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMakananCbActionPerformed
       setHargaMakanan();
    }//GEN-LAST:event_menuMakananCbActionPerformed

    private void makananBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makananBtnActionPerformed
        try{
            int hargaMakanan = Integer.parseInt(hargaMakananTxt.getText());
            int jumlahMakanan = Integer.parseInt(jumlahMakananTxt.getText());
            subTotalMakananTxt.setText("" + (hargaMakanan * jumlahMakanan));
        }catch(NumberFormatException e){
            subTotalMakananTxt.setText("0");
        }
    }//GEN-LAST:event_makananBtnActionPerformed

    private void minumanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minumanBtnActionPerformed
         try{
            int hargaMinuman = Integer.parseInt(hargaMinumanTxt.getText());
            int jumlahMinuman = Integer.parseInt(jumlahMinumanTxt.getText());
            subTotalMinumanTxt.setText("" + (hargaMinuman * jumlahMinuman));
        }catch(NumberFormatException e){
            subTotalMinumanTxt.setText("0");
        }
    }//GEN-LAST:event_minumanBtnActionPerformed

    private void menuMinumanCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMinumanCbActionPerformed
        setHargaMinuman();
    }//GEN-LAST:event_menuMinumanCbActionPerformed

    private void tambahkanMakanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkanMakanBtnActionPerformed
        if(cekKosong(true) == false){
            String menuItem = menuMakananCb.getSelectedItem().toString();
            if(cekDataTabel(menuItem) == false){
                int hrg = Integer.parseInt(hargaMakananTxt.getText());
                int kuantiti = Integer.parseInt(jumlahMakananTxt.getText());
                subTotalMakananTxt.setText("" + (hrg * kuantiti));
                
                menu.add(menuItem);
                harga.add(hargaMakananTxt.getText());
                jumlah.add(jumlahMakananTxt.getText());
                subtotal.add(subTotalMakananTxt.getText());
                
                setTabel();
            }
        }
        menuMakananCb.setSelectedIndex(0);
        hargaMakananTxt.setText("");
        jumlahMakananTxt.setText("");
        subTotalMakananTxt.setText("");
        
    }//GEN-LAST:event_tambahkanMakanBtnActionPerformed

    private void tambahkanMinumanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkanMinumanBtnActionPerformed
        if(cekKosong(true) == false){
            String menuItem = menuMinumanCb.getSelectedItem().toString();
            if(cekDataTabel(menuItem) == false){
                int hrg = Integer.parseInt(hargaMinumanTxt.getText());
                int kuantiti = Integer.parseInt(jumlahMinumanTxt.getText());
                subTotalMinumanTxt.setText("" + (hrg * kuantiti));
                
                menu.add(menuItem);
                harga.add(hargaMinumanTxt.getText());
                jumlah.add(jumlahMinumanTxt.getText());
                subtotal.add(subTotalMinumanTxt.getText());
                
                setTabel();
            }
        }
        menuMinumanCb.setSelectedIndex(0);
        hargaMinumanTxt.setText("");
        jumlahMinumanTxt.setText("");
        subTotalMinumanTxt.setText("");
    }//GEN-LAST:event_tambahkanMinumanBtnActionPerformed

    private void bayarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarBtnActionPerformed
        int totalBayar = Integer.parseInt(totalBayarTxt.getText());
        int jumlahBayar = Integer.parseInt(jumlahBayarTxt.getText());
        
        kembalianTxt.setText("" + (jumlahBayar - totalBayar));
    }//GEN-LAST:event_bayarBtnActionPerformed

    private void clearBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtActionPerformed
        totalTxt.setText("");
        ppnTxt.setText("");
        totalBayarTxt.setText("");
        jumlahBayarTxt.setText("");
        kembalianTxt.setText("");
        
        menu.clear();
        harga.clear();
        jumlah.clear();
        subtotal.clear();
        
        setTabel();
    }//GEN-LAST:event_clearBtActionPerformed

    private void subTotalMinumanTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTotalMinumanTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subTotalMinumanTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayarBtn;
    private javax.swing.JButton clearBt;
    private javax.swing.JTable dataTabel;
    private javax.swing.JTextField hargaMakananTxt;
    private javax.swing.JTextField hargaMinumanTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahBayarTxt;
    private javax.swing.JTextField jumlahMakananTxt;
    private javax.swing.JTextField jumlahMinumanTxt;
    private javax.swing.JTextField kembalianTxt;
    private javax.swing.JButton makananBtn;
    private javax.swing.JComboBox<String> menuMakananCb;
    private javax.swing.JComboBox<String> menuMinumanCb;
    private javax.swing.JButton minumanBtn;
    private javax.swing.JTextField ppnTxt;
    private javax.swing.JTextField subTotalMakananTxt;
    private javax.swing.JTextField subTotalMinumanTxt;
    private javax.swing.JButton tambahkanMakanBtn;
    private javax.swing.JButton tambahkanMinumanBtn;
    private javax.swing.JTextField totalBayarTxt;
    private javax.swing.JTextField totalTxt;
    // End of variables declaration//GEN-END:variables

}
